

class LoggingError(Exception):
    pass


class UsersError(Exception):
    pass
